spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${LOCAL_HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:demo_data.sql

  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
    default-schema: tasklist

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_EXPIRATION}
    refresh: ${JWT_REFRESH_EXPIRATION}
springdoc:
  override-with-generic-response: false